CadastroClientes/CadastroClientes/Models/ErrorViewModel.cs
namespace CadastroClientes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroClientes/CadastroClientes/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace CadastroClientes.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Atualizar()
        {
            return View();
        }
        public IActionResult Apagar()
        {
            return View();
        }
    }
}

CadastroClientes/CadastroClientes/Controllers/HomeController.cs
using CadastroClientes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroClientes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroClientes/CadastroClientes/Views/Cliente/Apagar.cshtml
@{
    ViewData["Title"] = "Remover Cliente";
}

<h1>REMOVER CLIENTE</h1>

CadastroClientes/CadastroClientes/Views/Cliente/Atualizar.cshtml
@{
    ViewData["Title"] = "Atualiza Cliente";
}

<h1>ATUALIZAR CLIENTE</h1>

CadastroClientes/CadastroClientes/Views/Cliente/Criar.cshtml
@{
    ViewData["Title"] = "Insere Cliente";
}

<h1>INSERIR CLIENTES</h1>

CadastroClientes/CadastroClientes/Views/Cliente/Index.cshtml
@{
    ViewData["Title"] = "Lista de Clientes";
}

<div class="text-center">
    <h1>LISTA DE CLIENTES</h1>
    <a role="button" class="btn btn-primary">Inserir</a>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Telefone</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>mark@email.com</td>
      <td>(11)98061-1234</td>
      <td>
           <div class="btn-group" role="group">
               <a role="button" class="btn btn-primary">Atualizar</a>
               <a role="button" class="btn btn-danger">Deletar</a>
           </div>
      </td>
    </tr>       
    <tr>
      <th scope="row">2</th>
      <td>Mark</td>
      <td>mark@email.com</td>
      <td>(11)98061-1234</td>
      <td>
           <div class="btn-group" role="group">
               <a role="button" class="btn btn-primary">Atualizar</a>
               <a role="button" class="btn btn-danger">Deletar</a>
           </div>
      </td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Mark</td>
      <td>mark@email.com</td>
      <td>(11)98061-1234</td>
      <td>
           <div class="btn-group" role="group">
               <a role="button" class="btn btn-primary">Atualizar</a>
               <a role="button" class="btn btn-danger">Deletar</a>
           </div>
      </td>
    </tr>
  </tbody>
</table>
</div>

CadastroClientes/CadastroClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro de Clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroClientes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro de Clientes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pietro Enrico Leal Guerra
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>